// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.Infrastructure.Persistence;

#nullable disable

namespace WarehouseManagement.Infrastructure.Migrations
{
    [DbContext(typeof(SqlServerApplicationDbContext))]
    [Migration("20260707074704_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("WarehouseManagement")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Products", "WarehouseManagement");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.StockBalance", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("WarehouseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockBalances", "WarehouseManagement");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.StockDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FromWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("ToWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("ToWarehouseId");

                    b.ToTable("StockDocuments", "WarehouseManagement");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.StockDocumentItem", b =>
                {
                    b.Property<Guid>("StockDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockDocumentId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockDocumentItems", "WarehouseManagement");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "WarehouseManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6712adb7-a20d-43e9-8b29-357271f3bd65"),
                            PasswordHash = "3c830e2af2e5db02e2f467634499d3c807e7b0c1b09c247a478c893703999b0e",
                            PasswordSalt = "6081de2f-df32-4e79-a844-772054b8fb32",
                            Phone = "09121234567",
                            Role = 10,
                            Username = "AdminUser"
                        },
                        new
                        {
                            Id = new Guid("92aa3814-ee96-4593-bdd3-cd613268137a"),
                            PasswordHash = "3c830e2af2e5db02e2f467634499d3c807e7b0c1b09c247a478c893703999b0e",
                            PasswordSalt = "6081de2f-df32-4e79-a844-772054b8fb32",
                            Phone = "09139876543",
                            Role = 20,
                            Username = "OperatorUser2"
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens", "WarehouseManagement");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Warehouses", "WarehouseManagement");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.StockBalance", b =>
                {
                    b.HasOne("WarehouseManagement.Domain.Entities.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("StockBalances")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.StockDocument", b =>
                {
                    b.HasOne("WarehouseManagement.Domain.Entities.Warehouse", "FromWarehouse")
                        .WithMany("OutgoingDocuments")
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarehouseManagement.Domain.Entities.Warehouse", "ToWarehouse")
                        .WithMany("IncomingDocuments")
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromWarehouse");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.StockDocumentItem", b =>
                {
                    b.HasOne("WarehouseManagement.Domain.Entities.Product", "Product")
                        .WithMany("StockDocumentItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Domain.Entities.StockDocument", "StockDocument")
                        .WithMany("StockDocumentItems")
                        .HasForeignKey("StockDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockDocument");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("WarehouseManagement.Domain.Entities.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.Product", b =>
                {
                    b.Navigation("StockBalances");

                    b.Navigation("StockDocumentItems");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.StockDocument", b =>
                {
                    b.Navigation("StockDocumentItems");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRefreshTokens");
                });

            modelBuilder.Entity("WarehouseManagement.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("IncomingDocuments");

                    b.Navigation("OutgoingDocuments");

                    b.Navigation("StockBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
