<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gridify" Version="2.19.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.3" />
  </ItemGroup>

</Project>
